image:
  repository: desenvolvedorio/devstore-web-mvc-ecommerce
  tag: "1.3.1"

readinessProbe:
  httpGet:
    path: /
    port: 443
    scheme: HTTPS
  initialDelaySeconds: 13
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 443
    scheme: HTTPS
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  port: 80
  targetPort: http

secretRefs:
  - status-connection

ingress:
  enabled: true
  hosts:
  - host: status.devstore.info
    paths:
    - path: /
      pathType: Prefix

pfx:
  enabled: true

environment:
  ASPNETCORE_URLS: http://+;https://+
  ENDPOINTS: "Identity API|https://api-identity/healthz-infra;BFF Checkout API|https://api-bff-checkout/healthz-infra;Catalog API|https://api-catalog/healthz-infra;Cart API|https://api-cart/healthz-infra;Billing API|https://api-billing/healthz-infra;Customer API|https://api-customer/healthz-infra;Orders API|https://api-orders/healthz-infra;"
