apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzbC5pbmZyYS5zdmM7UG9ydD01NDMyO0RhdGFiYXNlPURCQ3VzdG9tZXI7VXNlcklkPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzOw==
kind: Secret
metadata:
  creationTimestamp: null
  name: customer-connection
  namespace: devstore
