apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sqlserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sqlserver
        environment: test
        tier: database
        app: dev-store
      name: database
      namespace: infra
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Teste@123
        image: mcr.microsoft.com/mssql/server:2017-latest
        name: database
        resources: {}
        volumeMounts:
          - name: sql-data
            mountPath: /var/opt/mssql
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: infra
spec:
  selector:
    run: sqlserver
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi